name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-04"


 [vars]
 
DATABASE_URL="prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzgwYjIyODktODRkMi00NTJhLThhMTAtZTc3OWRiNGIzNTg4IiwidGVuYW50X2lkIjoiODM5MTkwM2U0OWJiMmY2MTFjMTgyYjAwMzM0NDdkMGY5MjE1YmUwNjcxNmQwODQzOWI3YmVjYzI4MDVlZTNkMSIsImludGVybmFsX3NlY3JldCI6IjZkYjQwODdhLThlZDUtNDVmYi1hNmM4LWMzNzBjYmUwZTYxMiJ9.lo4s_EPBlKeLnJo-TKySGBb8Rflc6JNbUMFMr8Ti8Uw"

JWT_SECRET=""